version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.53.0
    ports:
      - 16686:16686
      - 4318:4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
